### ISSUE TITLE
Play 2.8.0 Java  NoSuchMethodError Lscala/Function0;Lplay/api/MarkerContext 

### ISSUE THREAD

**Issue by lapidus79** [payintech/play-ebean#12]
Can't get 19.10 to work with Play 2.8.0 Java flavour. Stuck the below stacktrace when firing up in dev mode. Found this one: https://discuss.lightbend.com/t/ebean-for-play-2-8-x/5534 but I have jdbc dependecy included for sure, so that didn't help.
 

```
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: play.api.Logger$.info(Lscala/Function0;Lplay/api/MarkerContext;)V
  at play.db.ebean.dbmigration.PlayInitializer.<init>(PlayInitializer.scala:15)
  at play.db.ebean.dbmigration.PlayModule.bindings(PlayModule.scala:15):
Binding(class play.db.ebean.dbmigration.PlayInitializer to self eagerly) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$4)
  while locating play.db.ebean.dbmigration.PlayInitializer

1 error]
        at play.core.server.DevServerStart$$anon$1.reload(DevServerStart.scala:210)
	at play.core.server.DevServerStart$$anon$1.get(DevServerStart.scala:141)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:296)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:186)
```

When firing up in dev mode.

**Comment by PierreAdam** [comment]
I think it should be fixed in the next version. I'm gonna do one more test on a real project just to check backward compatibility. If it's all good, I'm gonna release the 20.02 today. This version will support play 2.8.0+

**Comment by PierreAdam** [comment]
Fixed in 20.02. Sorry for the delay.
